/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package screen;

import control.HomeController;
import data.model.AccountType;
import data.model.Utils;
import javax.swing.JFrame;
import javax.swing.JOptionPane;

/**
 *
 * @author hoang
 */
public class HomeView extends javax.swing.JFrame {

    private final HomeController homeController;

    public HomeView(HomeController homeController) {
        initComponents();
        this.homeController = homeController;
        decentralizationUserType();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jMenuItem2 = new javax.swing.JMenuItem();
        jLabel1 = new javax.swing.JLabel();
        jLabelUser = new javax.swing.JLabel();
        jLabelTeacher = new javax.swing.JLabel();
        jLabelStudent = new javax.swing.JLabel();
        jLabelMark = new javax.swing.JLabel();
        jLabelSetting = new javax.swing.JLabel();
        jMenuBar1 = new javax.swing.JMenuBar();
        jMenu1 = new javax.swing.JMenu();
        jMenuItem1 = new javax.swing.JMenuItem();
        jMenuItem3 = new javax.swing.JMenuItem();

        jMenuItem2.setText("jMenuItem2");

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel1.setText("Xin chào");

        jLabelUser.setText("Admin,");

        jLabelTeacher.setIcon(new javax.swing.ImageIcon(getClass().getResource("/asset/teacher.png"))); // NOI18N
        jLabelTeacher.setText("Quản lý thông tin giáo viên");
        jLabelTeacher.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabelTeacherMouseClicked(evt);
            }
        });

        jLabelStudent.setIcon(new javax.swing.ImageIcon(getClass().getResource("/asset/student.png"))); // NOI18N
        jLabelStudent.setText("Quản lý thông tin sinh viên");
        jLabelStudent.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabelStudentMouseClicked(evt);
            }
        });

        jLabelMark.setIcon(new javax.swing.ImageIcon(getClass().getResource("/asset/marking.png"))); // NOI18N
        jLabelMark.setText("Quản lý điểm sinh viên");
        jLabelMark.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabelMarkMouseClicked(evt);
            }
        });

        jLabelSetting.setIcon(new javax.swing.ImageIcon(getClass().getResource("/asset/performance.png"))); // NOI18N
        jLabelSetting.setText("Cấu hình");

        jMenuBar1.setBackground(new java.awt.Color(255, 255, 255));

        jMenu1.setText("Tài khoản");

        jMenuItem1.setText("Sửa thông tin tài khỏan");
        jMenuItem1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem1ActionPerformed(evt);
            }
        });
        jMenu1.add(jMenuItem1);

        jMenuItem3.setText("Đăng xuất");
        jMenuItem3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem3ActionPerformed(evt);
            }
        });
        jMenu1.add(jMenuItem3);

        jMenuBar1.add(jMenu1);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jLabel1)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabelUser))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(94, 94, 94)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabelTeacher, javax.swing.GroupLayout.PREFERRED_SIZE, 250, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabelMark))
                        .addGap(67, 67, 67)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabelSetting)
                            .addComponent(jLabelStudent))))
                .addContainerGap(102, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(jLabelUser))
                .addGap(46, 46, 46)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabelTeacher)
                    .addComponent(jLabelStudent))
                .addGap(52, 52, 52)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabelMark)
                    .addComponent(jLabelSetting))
                .addContainerGap(57, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jMenuItem1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jMenuItem1ActionPerformed

    private void jLabelTeacherMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabelTeacherMouseClicked
        homeController.requestTeacherManagerScreen();
    }//GEN-LAST:event_jLabelTeacherMouseClicked

    private void jLabelStudentMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabelStudentMouseClicked
        homeController.requestStudentManagerScreen();
    }//GEN-LAST:event_jLabelStudentMouseClicked

    private void jLabelMarkMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabelMarkMouseClicked
        homeController.requestMarkManagerScreen();
    }//GEN-LAST:event_jLabelMarkMouseClicked

    private void jMenuItem3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem3ActionPerformed
        this.dispose();
    }//GEN-LAST:event_jMenuItem3ActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabelMark;
    private javax.swing.JLabel jLabelSetting;
    private javax.swing.JLabel jLabelStudent;
    private javax.swing.JLabel jLabelTeacher;
    private javax.swing.JLabel jLabelUser;
    private javax.swing.JMenu jMenu1;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JMenuItem jMenuItem1;
    private javax.swing.JMenuItem jMenuItem2;
    private javax.swing.JMenuItem jMenuItem3;
    // End of variables declaration//GEN-END:variables

    public void setUpUserName(String userName) {
        jLabelUser.setText(userName + ",");
    }

    public void showClosedConfirmMessage() {
        int confirmed = JOptionPane.showConfirmDialog(this,
                "Bạn có chắc muốn thoát màn hình chính?", "Thoát",
                JOptionPane.YES_NO_OPTION);

        if (confirmed == JOptionPane.YES_OPTION) {
            dispose();
        } else {
            setDefaultCloseOperation(JFrame.DO_NOTHING_ON_CLOSE);
        }
    }

    public final void decentralizationUserType() {
        if (Utils.currentAccountType == AccountType.ADMIN) {
            jLabelTeacher.setEnabled(true);
            jLabelSetting.setEnabled(true);
            jLabelStudent.setEnabled(true);
            jLabelMark.setEnabled(false);
        } else {
            jLabelTeacher.setEnabled(false);
            jLabelSetting.setEnabled(false);
            jLabelStudent.setEnabled(false);
            jLabelMark.setEnabled(true);
        }
    }
}
